src/main/java/Task.java
Made abstract class for Task and implemented:
1. setCompletedStatus()
2. getCompleted()
3. display()
=> 11 feature 11 implement the abstract class task

src/main/java/PhoneNumberTask.java
The features for the Phone Number Task Use Case
=> Code for the Phone Number Task Use Case.

src/main/java/Authenticator.java, src/main/java/Menu.java, src/main/java/PhoneNumberTask.java
Removed the overriding features after changes in abstract class and made a resources folder
=> 20 feature 18 phone number task back end

src/main/java/AssignmentTask.java
changed to static design we talked about
=> changed AssignmentTask methods to static to match the Task changes.

src/main/java/controller/PhoneNumberTaskController.java, src/main/java/entities/GameMaster.java, src/main/java/view/HeatAdjustmentTaskView.java, src/main/java/view/PhoneNumberTaskView.java
It now accesses the Task subclasses directly without creating instances of them in order to utilize the static method functionality.
=> Updated the GameMaster Backend

src/main/java/controller/HeatAdjustmentTaskController.java, src/main/java/entities/GameMaster.java, src/main/java/entities/HeatAdjustmentTask.java, src/main/java/entities/LifeMaster.java, src/main/java/view/HeatAdjustmentTaskView.java
I've completed the first version of the back-end, view and controller of the Heat Adjustment Task. I've done minimal testing, so I just know that the view works fine.
=> HeatAdjustmentTask Back-End, View and Controller

src/main/java/controller/ClickTaskController.java, src/main/java/entities/ClickTask.java, src/main/java/view/ClickTaskView.java
Changed everything in ClickTask.java, ClickTaskController.java, ClickTaskView.java to static.
=> Changed to Click Task Static

src/main/java/entities/MemoryTask.java
memory task backed pull request
=> 25 memory task backend

src/main/java/controller/ClickTaskController.java, src/main/java/entities/ClickTask.java, src/main/java/view/ClickTaskView.java
I added javadoc for ClickTask.java, ClickTaskController.java, and ClickTaskView.java. Also, please note I forgot to change the descriptions for my first commit in this pull request, ignore them!
=> Added javadoc for ClickTask related files

src/main/java/controller/MemoryTaskController.java, src/main/java/controller/PhoneNumberTaskController.java, src/main/java/entities/MemoryTask.java, src/main/java/entities/PhoneNumberTask.java, src/main/java/resources/users.txt, src/main/java/view/MemoryTaskView.java, src/main/java/view/PhoneNumberTaskView.java
Additions to the phonenumber view and renamed variables to follow naming conventions
=> Changes to the phonenumber view

src/test/java/AssignmentTaskTest.java
Pls check over my test cases for implemented methods!
=> wrote test cases for AssignmentTask

src/main/java/controller/TriviaTaskController.java, src/main/java/controller/WireTaskController.java, src/main/java/entities/TriviaTask.java, src/main/java/entities/WireTask.java, src/test/java/AssignmentTaskTest.java
Some classes had to be changed, specifically the get/set calls in some use case and test classes, in order to work with the changes made in my previous pull request.
=> Updated needed files to fit with new status functionality

src/test/java/AssignmentTaskTest.java
after Elena changed the implementation a bit, the test started to fail so I corrected the issue
=> fixed the issue with checking AssignmentTaskTest

src/test/java/ClickTaskTest.java
I've added test cases for ClickTask.java. I don't know how to get rid of the previous two commits, please look into the latest rwo commit with description "Added Javadoc for ClickTaskTest.java." and "Wrote test cases for ClickTask.java." for changes.
=> Test Cases for Click Task

src/main/java/controller/NonGameController.java, src/main/java/entities/Authenticator.java, src/main/java/entities/ClickTask.java, src/main/java/entities/Menu.java, src/main/java/presentor/AuthenticatorPresentor.java, src/main/java/presentor/HighscorePresentor.java, src/main/java/view/AuthenticatorView.java, src/main/java/view/StartView.java
I was passing the values wrong so I redid my presenters, feel free to use this as an example :p
=> modified menu and authenticator presenters to follow clean architecture

src/main/java/controller/AssignmentTaskController.java, src/main/java/controller/ClickTaskController.java, src/main/java/controller/GameMasterController.java, src/main/java/controller/HeatAdjustmentTaskController.java, src/main/java/controller/MemoryTaskController.java, src/main/java/controller/NonGameController.java, src/main/java/controller/PhoneNumberTaskController.java, src/main/java/controller/TriviaTaskController.java, src/main/java/controller/WireTaskController.java, src/main/java/presenter/AuthenticatorPresentor.java, src/main/java/presenter/HighscorePresentor.java, src/main/java/usecases/AssignmentTask.java, src/main/java/usecases/Authenticator.java, src/main/java/usecases/ClickTask.java, src/main/java/usecases/GameMaster.java, src/main/java/usecases/HeatAdjustmentTask.java, src/main/java/usecases/LifeMaster.java, src/main/java/usecases/MemoryTask.java, src/main/java/usecases/Menu.java, src/main/java/usecases/PhoneNumberTask.java, src/main/java/usecases/Task.java, src/main/java/usecases/TriviaTask.java, src/main/java/usecases/WireTask.java, src/main/java/view/GameMasterView.java, src/test/java/AssignmentTaskTest.java, src/test/java/AuthenticatorTest.java, src/test/java/ClickTaskTest.java, src/test/java/LifeMasterTest.java
Changed entities to use cases and moved user to entities
=> Renaming folders

src/main/java/usecases/GameMaster.java, src/test/java/GameMasterTest.java
I added test cases for Game Master and changed the chooseTask method from GameMaster.java from private to public.
=> Game Master Test

src/main/java/view/GameMasterView.java, src/test/java/ClickTaskTest.java
Fixed some Test file assertion errors
=> Fixed errors

src/main/java/controller/ClickTaskController.java, src/main/java/presenter/ClickTaskPresenter.java, src/main/java/usecases/ClickTask.java, src/main/java/view/ClickTaskView.java
Here's what I did:
1. I added missing Javadoc for ClickTask.java, ClickTaskController.java, and ClickTaskView.java.
2. I added a ClickTaskPresenter file in the presenter package.
3. ClickTask won't generate 0 neededClicks anymore.0
=> Javadoc and Random Number of Click task

src/main/java/presenter/WireTaskPresenter.java, src/main/java/usecases/WireTask.java, src/main/java/view/WireTaskView.java
-implemented the skeleton for view class, missing the click events
=> 27 wiretask

src/main/java/presenter/ClickTaskPresenter.java, src/main/java/view/ClickTaskView.java, src/test/java/ClickTaskTest.java, src/test/java/controller/ClickTaskControllerTest.java, src/test/java/presenter/ClickTaskPresenterTest.java
1. I completed the ClickTaskPresenter.java and modified ClickTaskView.java accordingly.
2. Fixed setCurrentClicksPortion method.
=> Click Task Presenter and ClickTaskTest bug fixed

src/test/java/controller/AssignmentTaskControllerTest.java
=> finished implementing test cases for AssignmentTaskController

src/main/java/usecases/GameMaster.java, src/main/java/usecases/LifeMaster.java, src/main/java/view/GameMasterView.java
This is a temporary change so our game doesn't crash while the game over functionality isn't finished
=> Made window close when game is over 

src/main/java/usecases/LifeMaster.java
simply added a system exit at the end of the game
=> Game ends when you lose all your lives

src/main/java/view/TriviaTaskView.java
made some edits to the view
DELETED unnecessary and redundant comments
also made small edit to submit button action listener
=> Trivia view edits

src/main/java/controller/TriviaTaskController.java, src/main/java/presenter/TriviaTaskPresenter.java, src/main/java/usecases/TriviaTask.java
added javadocs
resolved warnings
deleted unneessary comments and cleaned up code a bit!
=> Talia add javadocs

src/test/java/controller/ClickTaskControllerTest.java
Finished test cases for ClickTaskController.java.
=> Tests for ClickTaskController.java

src/main/java/controller/TriviaTaskController.java, src/main/java/usecases/TriviaTask.java, src/test/java/usecases/MemoryTaskTest.java, src/test/java/usecases/TriviaTaskTest.java
tests for:
trivia task usecase
memory task usecase
=> Trivia task tests

src/main/java/controller/TriviaTaskController.java, src/main/java/presenter/TriviaTaskPresenter.java, src/main/java/usecases/TriviaTask.java, src/main/java/view/TriviaTaskView.java
=> Talia javadocs dec8

src/main/java/view/AssignmentTaskView.java
I did a last minute cleanup in grammar and unused imports
=> last minute cleanup fixing typos and unused imports
